"""Package a whole design - CAD, reports and all - into one file.

An export that lands as fourteen loose files in a folder is awkward to send to
somebody, to attach to an order, or to keep with the rest of a project. This
writes the same outputs into a single ``.zip``, laid out so it is obvious what
to do with each part, with a manifest that says what everything is and what the
mating dimensions are.

Layout
------
::

    <name>.zip
      README.txt              what is in here and how the parts go together
      print/                  STL solids, ready to slice
      cad/                    STEP solids, SVG templates, DXF, Fusion script
      reports/                engineering report, manufacturing guide, PDF

This module is deliberately the one place that knows about both
:mod:`rocketopt.cad` and :mod:`rocketopt.reports`; neither imports the other.
"""

from __future__ import annotations

import datetime as _dt
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Final

from rocketopt.cad.parts import (
    DEFAULT_TOLERANCES,
    PrintTolerances,
    body_tube_of,
    printable_parts,
    spigot_length,
)
from rocketopt.geometry.rocket import Rocket
from rocketopt.utils.logging import get_logger

if TYPE_CHECKING:  # pragma: no cover
    from rocketopt.flight.simulation import FlightResult

_log = get_logger(__name__)

__all__ = ["BundleContents", "write_bundle"]

_MM: Final[float] = 1e3
"""Metres to millimetres."""

_PRINT_DIR: Final[str] = "print"
_CAD_DIR: Final[str] = "cad"
_REPORT_DIR: Final[str] = "reports"

# Which of the loose CAD outputs belongs in which folder of the archive.
_PRINT_SUFFIXES: Final[frozenset[str]] = frozenset({".stl"})


@dataclass(frozen=True, slots=True)
class BundleContents:
    """What a written bundle turned out to contain.

    Attributes
    ----------
    path:
        The archive written.
    names:
        Every entry in it, in archive order.
    uncompressed_bytes:
        Total size of the contents before compression.
    """

    path: Path
    names: tuple[str, ...]
    uncompressed_bytes: int

    @property
    def file_count(self) -> int:
        """Number of files in the archive."""
        return len(self.names)


def _safe_stem(name: str) -> str:
    """Turn a design name into something usable as a file name."""
    cleaned = "".join(
        character if character.isalnum() or character in "-_" else "_"
        for character in name.strip()
    )
    return cleaned.strip("_") or "rocket"


def _manifest(
    rocket: Rocket,
    entries: list[tuple[str, int]],
    tolerances: PrintTolerances,
) -> str:
    """Build the README that goes at the root of the archive.

    Parameters
    ----------
    rocket:
        The design.
    entries:
        ``(archive name, size in bytes)`` for every file included.
    tolerances:
        The print clearances the solids were built with.

    Returns
    -------
    str
        The manifest text.
    """
    tube = body_tube_of(rocket)
    mount = rocket.motor_mount
    motor = rocket.motor.motor
    spigot = spigot_length(rocket, tolerances)
    spigot_mm = rocket.nose.shoulder_outer_radius * 2 * _MM
    bore_mm = tube.inner_radius * 2 * _MM
    parts = printable_parts(rocket, tolerances)

    listing = "\n".join(
        f"  {name:<44} {size / 1024:>8.1f} kB" for name, size in entries
    )
    part_lines = "\n".join(
        f"  {part.name:<14} x{part.quantity:<3} {part.description}" for part in parts
    )

    return f"""{rocket.name}
{"=" * len(rocket.name)}

Generated by RocketOpt on {_dt.date.today().isoformat()}.

Design
------
  Motor              {rocket.motor.designation}
  Overall length     {rocket.length * _MM:.1f} mm
  Body diameter      {rocket.reference_diameter * _MM:.2f} mm
  Body tube bore     {tube.inner_radius * 2 * _MM:.2f} mm
  Nose               {rocket.nose.shape.label}, {rocket.nose.length * _MM:.1f} mm
  Fins               {rocket.fins.count} x {rocket.fins.airfoil.label.lower()} section
  Dry mass           {rocket.dry_mass * _MM:.1f} g
  Lift-off mass      {rocket.loaded_mass * _MM:.1f} g

How the parts fit together
--------------------------
  Nose cone spigot   {spigot_mm:.2f} mm nominal, {spigot * _MM:.1f} mm deep,
                     into the {bore_mm:.2f} mm bore
  Motor mount        {mount.outer_diameter * _MM:.2f} mm outside,
                     {mount.inner_diameter * _MM:.2f} mm bore,
                     {mount.length * _MM:.1f} mm long,
                     for a {motor.diameter * _MM:.1f} mm case
  Print clearances   {tolerances.spigot_clearance * _MM:.2f} mm on the spigot,
                     {tolerances.mount_clearance * _MM:.2f} mm on the mount,
                     {tolerances.motor_clearance * _MM:.2f} mm on the motor bore
                     (all on diameter, taken off the part that goes inside)

Every solid was checked before it was written: the mating diameters were
measured off the meshes themselves, and each part is a closed, manifold,
outward-facing solid. Slice the STLs as they are - they are in millimetres and
each one already sits on the bed the right way up.

Parts
-----
{part_lines}

Contents
--------
{listing}
"""


def write_bundle(
    rocket: Rocket,
    path: str | Path,
    *,
    flight: FlightResult | None = None,
    tolerances: PrintTolerances = DEFAULT_TOLERANCES,
    include_reports: bool = True,
) -> BundleContents:
    """Write every output for a design into a single archive.

    Parameters
    ----------
    rocket:
        The design.
    path:
        Destination ``.zip`` path. A directory, or a path without a suffix, is
        treated as a place to put ``<design name>.zip``.
    flight:
        A flown trajectory for the reports. One is simulated at standard
        conditions when not given.
    tolerances:
        Print clearances and tessellation for the solids.
    include_reports:
        Include the engineering report and manufacturing guide. Turning this
        off skips the flight simulation too, which is most of the time taken.

    Returns
    -------
    BundleContents
        The archive written and what went into it.

    Raises
    ------
    rocketopt.cad.validation.AssemblyValidationError
        If the design's parts would not assemble or would not slice. Nothing is
        written in that case.
    """
    from rocketopt.cad.exporters import export_all

    destination = Path(path).expanduser()
    if destination.is_dir() or not destination.suffix:
        destination = destination / f"{_safe_stem(rocket.name)}.zip"
    destination.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="rocketopt-bundle-") as scratch:
        staging = Path(scratch)
        written = export_all(rocket, staging, tolerances=tolerances)

        staged: list[tuple[Path, str]] = []
        for file in written:
            folder = _PRINT_DIR if file.suffix in _PRINT_SUFFIXES else _CAD_DIR
            staged.append((file, f"{folder}/{file.name}"))

        if include_reports:
            staged.extend(_stage_reports(rocket, staging, flight))

        entries = [(name, file.stat().st_size) for file, name in staged]
        manifest = _manifest(rocket, entries, tolerances)

        destination.unlink(missing_ok=True)
        with zipfile.ZipFile(
            destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6
        ) as archive:
            archive.writestr("README.txt", manifest)
            for file, name in staged:
                archive.write(file, name)
            names = tuple(archive.namelist())

    total = sum(size for _, size in entries) + len(manifest.encode("utf-8"))
    _log.info(
        "Bundled %d file(s) for %s into %s (%.0f kB)",
        len(names),
        rocket.name,
        destination,
        destination.stat().st_size / 1024,
    )
    return BundleContents(
        path=destination.resolve(), names=names, uncompressed_bytes=total
    )


def _stage_reports(
    rocket: Rocket, staging: Path, flight: FlightResult | None
) -> list[tuple[Path, str]]:
    """Write the reports into the staging directory.

    Parameters
    ----------
    rocket:
        The design.
    staging:
        Directory to write into.
    flight:
        A flown trajectory, or ``None`` to simulate one.

    Returns
    -------
    list of tuple
        ``(file, archive name)`` for each report written.
    """
    from rocketopt.flight.environment import LaunchConditions
    from rocketopt.flight.simulation import SimulationConfig, simulate
    from rocketopt.reports.bom import write_manufacturing_guide
    from rocketopt.reports.engineering import write_markdown_report

    if flight is None:
        flight = simulate(
            rocket, LaunchConditions.standard(), SimulationConfig(six_dof=True)
        )

    staged = [
        (
            write_markdown_report(rocket, flight, staging / "engineering_report.md"),
            f"{_REPORT_DIR}/engineering_report.md",
        ),
        (
            write_manufacturing_guide(rocket, staging / "manufacturing_guide.md"),
            f"{_REPORT_DIR}/manufacturing_guide.md",
        ),
    ]

    from rocketopt.reports.pdf import PDF_AVAILABLE

    if PDF_AVAILABLE:
        from rocketopt.reports.pdf import write_pdf_report

        staged.append(
            (
                write_pdf_report(rocket, flight, staging / "engineering_report.pdf"),
                f"{_REPORT_DIR}/engineering_report.pdf",
            )
        )
    else:
        _log.info(
            "ReportLab is not installed, so the bundle has no PDF. "
            "Install with: pip install 'rocketopt[reports]'"
        )

    return staged
