"""Motor model: thrust curves, mass history and derived performance figures.

Design note on thrust-curve provenance
--------------------------------------
There are two ways a :class:`ThrustCurve` reaches this module:

*Measured* (``ThrustCurveSource.MEASURED``)
    Parsed from a RASP ``.eng`` file, which is the format used by
    ThrustCurve.org and by the NAR Standards & Testing committee to publish
    static-test data. These are real measurements and are always preferred.

*Synthesised* (``ThrustCurveSource.SYNTHESISED``)
    Generated by :func:`synthesise_black_powder_curve` from the motor's
    published certified scalars. The generator solves for a shape parameter
    such that the resulting curve reproduces the certified total impulse,
    average thrust, peak thrust and burn time **exactly**. The curve therefore
    integrates correctly and has the right peak, but its detailed shape is a
    model of black-powder combustion rather than a measurement.

Any analysis that depends only on integrated quantities (apogee, burnout
velocity, total impulse) is insensitive to this distinction. Analyses that
depend on instantaneous thrust detail - peak airframe loads, rail-exit
acceleration - should use a measured curve. :meth:`Motor.provenance_warning`
returns a non-empty string whenever a synthesised curve is in use so that
reports can say so plainly.

References
----------
[1] Sutton, G. P., & Biblarz, O. (2016). *Rocket Propulsion Elements*, 9th ed.,
    Ch. 2 (total impulse, specific impulse) and Ch. 12 (solid grain burn).
[2] National Association of Rocketry, Standards & Testing Committee. *Model
    Rocket Motor Certification Procedures*, and the published certified motor
    data sheets.
[3] Coker, J. (2020). *RASP Engine File Format Specification*,
    ThrustCurve.org.
[4] Nakka, R. A. (2001). *Solid Propellant Rocket Motor Design and Testing*,
    Ch. 3 - pressure/thrust history of a progressive-then-regressive grain.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Final

import numpy as np
from numpy.typing import NDArray
from scipy.optimize import brentq

from rocketopt.utils.constants import G0
from rocketopt.utils.logging import get_logger

_log = get_logger(__name__)

__all__ = [
    "ThrustCurveSource",
    "ThrustCurve",
    "Motor",
    "MotorConfiguration",
    "synthesise_black_powder_curve",
    "impulse_class",
]

# Shape breakpoints for the synthesised black-powder curve, as fractions of
# total burn time. Chosen to match the qualitative pressure history of an
# Estes-type grain: a fast ignition transient while the conical core burns
# (progressive), a sharp drop as the core is consumed, a long sustained
# end-burn (neutral), and a tail-off as the grain thins. See [4], Fig. 3-6.
_TAU_RISE: Final[float] = 0.10
"""Fraction of burn time spent rising from ignition to peak thrust."""

_TAU_DECAY_END: Final[float] = 0.18
"""Fraction of burn time at which the post-peak drop reaches the plateau."""

_TAU_TAIL_START: Final[float] = 0.80
"""Fraction of burn time at which the final tail-off begins."""

_PLATEAU_DROOP: Final[float] = 0.85
"""Plateau thrust at ``_TAU_TAIL_START`` as a fraction of its value at
``_TAU_DECAY_END``; the burning surface slowly regresses."""

_RISE_EXPONENT: Final[float] = 1.5
"""Exponent of the ignition transient. Chamber pressure rises faster than
linearly as the igniter lights progressively more grain surface [4]."""


class ThrustCurveSource(str, Enum):
    """Provenance of a thrust curve."""

    MEASURED = "measured"
    """Static-test data parsed from a RASP ``.eng`` file."""

    SYNTHESISED = "synthesised"
    """Generated from certified scalars by a burn model."""


def _shape_mean(plateau: float) -> float:
    """Mean value of the normalised thrust shape for a given plateau level.

    The shape is piecewise and its integral is affine in ``plateau``, so this
    is evaluated in closed form rather than numerically.

    Parameters
    ----------
    plateau:
        Sustained thrust level as a fraction of peak thrust, in ``(0, 1]``.

    Returns
    -------
    float
        The mean of the shape over ``tau`` in ``[0, 1]``, equal to the ratio
        of average thrust to peak thrust that this shape produces.
    """
    # Segment 1: rise, s = (tau / tau_r) ** n, from 0 to 1.
    # Integral = tau_r / (n + 1).
    rise = _TAU_RISE / (_RISE_EXPONENT + 1.0)

    # Segment 2: linear decay from 1 down to `plateau`.
    decay_span = _TAU_DECAY_END - _TAU_RISE
    decay = decay_span * (1.0 + plateau) / 2.0

    # Segment 3: linear droop from `plateau` to `plateau * _PLATEAU_DROOP`.
    plateau_span = _TAU_TAIL_START - _TAU_DECAY_END
    plateau_mean = plateau * (1.0 + _PLATEAU_DROOP) / 2.0
    sustain = plateau_span * plateau_mean

    # Segment 4: linear tail-off from `plateau * _PLATEAU_DROOP` to zero.
    tail_span = 1.0 - _TAU_TAIL_START
    tail = tail_span * plateau * _PLATEAU_DROOP / 2.0

    return rise + decay + sustain + tail


def _shape(tau: NDArray[np.float64], plateau: float) -> NDArray[np.float64]:
    """Evaluate the normalised thrust shape.

    Parameters
    ----------
    tau:
        Normalised time, ``t / burn_time``, in ``[0, 1]``.
    plateau:
        Sustained thrust as a fraction of peak thrust.

    Returns
    -------
    numpy.ndarray
        Thrust as a fraction of peak thrust, peaking at exactly 1.0.
    """
    s = np.zeros_like(tau, dtype=np.float64)

    rise = tau < _TAU_RISE
    s[rise] = (tau[rise] / _TAU_RISE) ** _RISE_EXPONENT

    decay = (tau >= _TAU_RISE) & (tau < _TAU_DECAY_END)
    frac = (tau[decay] - _TAU_RISE) / (_TAU_DECAY_END - _TAU_RISE)
    s[decay] = 1.0 + frac * (plateau - 1.0)

    sustain = (tau >= _TAU_DECAY_END) & (tau < _TAU_TAIL_START)
    frac = (tau[sustain] - _TAU_DECAY_END) / (_TAU_TAIL_START - _TAU_DECAY_END)
    s[sustain] = plateau * (1.0 + frac * (_PLATEAU_DROOP - 1.0))

    tail = (tau >= _TAU_TAIL_START) & (tau <= 1.0)
    frac = (tau[tail] - _TAU_TAIL_START) / (1.0 - _TAU_TAIL_START)
    s[tail] = plateau * _PLATEAU_DROOP * (1.0 - frac)

    return s


def synthesise_black_powder_curve(
    total_impulse: float,
    peak_thrust: float,
    burn_time: float,
    *,
    n_points: int = 120,
) -> ThrustCurve:
    """Build a thrust curve matching published certified scalars exactly.

    The normalised shape has one free parameter, the plateau level. It is
    solved so that ``mean(shape) == average_thrust / peak_thrust``, where
    ``average_thrust = total_impulse / burn_time``. Scaling the shape by
    ``peak_thrust`` then reproduces the peak, the average, the burn time and
    hence the total impulse simultaneously.

    Parameters
    ----------
    total_impulse:
        Certified total impulse [N*s].
    peak_thrust:
        Certified maximum thrust [N].
    burn_time:
        Certified burn time [s].
    n_points:
        Number of samples in the generated curve.

    Returns
    -------
    ThrustCurve
        A curve tagged :attr:`ThrustCurveSource.SYNTHESISED`.

    Raises
    ------
    ValueError
        If the inputs are non-positive, or if the implied average-to-peak
        thrust ratio cannot be produced by the burn model. The latter means
        the quoted scalars are mutually inconsistent - for example a peak
        thrust lower than the average.
    """
    if total_impulse <= 0.0 or peak_thrust <= 0.0 or burn_time <= 0.0:
        raise ValueError(
            "total_impulse, peak_thrust and burn_time must all be positive; "
            f"got {total_impulse}, {peak_thrust}, {burn_time}"
        )

    average_thrust = total_impulse / burn_time
    target_ratio = average_thrust / peak_thrust

    lo_ratio = _shape_mean(1e-3)
    hi_ratio = _shape_mean(1.0)
    if not lo_ratio < target_ratio < hi_ratio:
        raise ValueError(
            f"Average/peak thrust ratio {target_ratio:.3f} is outside the range "
            f"({lo_ratio:.3f}, {hi_ratio:.3f}) this black-powder burn model can "
            f"produce. Check that total_impulse={total_impulse} N*s, "
            f"peak_thrust={peak_thrust} N and burn_time={burn_time} s are "
            f"mutually consistent."
        )

    plateau = brentq(
        lambda p: _shape_mean(p) - target_ratio,
        1e-3,
        1.0,
        xtol=1e-12,
        rtol=1e-14,
    )

    # Sample densely through the ignition transient where curvature is highest,
    # and include every breakpoint exactly so the piecewise integral is exact.
    tau = np.unique(
        np.concatenate(
            [
                np.linspace(0.0, _TAU_DECAY_END, n_points // 3),
                np.linspace(_TAU_DECAY_END, _TAU_TAIL_START, n_points // 3),
                np.linspace(_TAU_TAIL_START, 1.0, n_points // 3),
                np.array([_TAU_RISE, _TAU_DECAY_END, _TAU_TAIL_START]),
            ]
        )
    )

    times = tau * burn_time
    thrusts = _shape(tau, float(plateau)) * peak_thrust

    curve = ThrustCurve(
        times=times,
        thrusts=thrusts,
        source=ThrustCurveSource.SYNTHESISED,
    )

    # The trapezoidal integral of a piecewise-linear shape sampled at every
    # breakpoint is exact, so this should agree to round-off. Rescale the
    # interior anyway so the guarantee in this docstring holds numerically.
    scale = total_impulse / curve.total_impulse
    if not np.isclose(scale, 1.0, rtol=1e-6):
        _log.debug("Rescaling synthesised curve by %.9f to match total impulse", scale)
    return ThrustCurve(
        times=times,
        thrusts=thrusts * scale,
        source=ThrustCurveSource.SYNTHESISED,
    )


@dataclass(frozen=True, slots=True)
class ThrustCurve:
    """A tabulated thrust-versus-time history.

    Thrust between samples is linearly interpolated, which is the convention
    the RASP format assumes [3]. Outside ``[0, burn_time]`` the thrust is zero.

    Attributes
    ----------
    times:
        Monotonically increasing sample times [s], starting at or after 0.
    thrusts:
        Thrust at each sample [N], non-negative.
    source:
        Provenance of the data; see :class:`ThrustCurveSource`.
    """

    times: NDArray[np.float64]
    thrusts: NDArray[np.float64]
    source: ThrustCurveSource = ThrustCurveSource.MEASURED
    _cumulative_impulse: NDArray[np.float64] = field(
        default_factory=lambda: np.zeros(0), repr=False, compare=False
    )
    """Impulse delivered up to each sample time [N*s]. Built in __post_init__."""

    def __post_init__(self) -> None:
        """Validate and normalise the tabulated data."""
        times = np.asarray(self.times, dtype=np.float64)
        thrusts = np.asarray(self.thrusts, dtype=np.float64)

        if times.ndim != 1 or thrusts.ndim != 1:
            raise ValueError("times and thrusts must be one-dimensional")
        if times.size != thrusts.size:
            raise ValueError(
                f"times and thrusts must be the same length; "
                f"got {times.size} and {thrusts.size}"
            )
        if times.size < 2:
            raise ValueError("a thrust curve needs at least two samples")
        if np.any(np.diff(times) <= 0.0):
            raise ValueError("times must be strictly increasing")
        if times[0] < 0.0:
            raise ValueError("times must not be negative")
        if np.any(thrusts < 0.0):
            raise ValueError("thrust must not be negative")
        if not np.all(np.isfinite(times)) or not np.all(np.isfinite(thrusts)):
            raise ValueError("thrust curve contains non-finite values")

        # Precompute the cumulative impulse at every sample. Without this,
        # impulse_to() has to integrate the whole curve on every call, and the
        # flight simulator calls it once per derivative evaluation - several
        # thousand times per flight. Trading a few hundred bytes for that is
        # the single largest performance win in the simulation.
        segment = 0.5 * (thrusts[1:] + thrusts[:-1]) * np.diff(times)
        cumulative = np.concatenate([[0.0], np.cumsum(segment)])

        # Frozen dataclass: rebind through object.__setattr__ so the stored
        # arrays are always float64 and read-only.
        times.flags.writeable = False
        thrusts.flags.writeable = False
        cumulative.flags.writeable = False
        object.__setattr__(self, "times", times)
        object.__setattr__(self, "thrusts", thrusts)
        object.__setattr__(self, "_cumulative_impulse", cumulative)

    @property
    def burn_time(self) -> float:
        """Time from ignition to the last tabulated sample [s]."""
        return float(self.times[-1])

    @property
    def total_impulse(self) -> float:
        """Area under the thrust curve [N*s].

        Read from the precomputed cumulative impulse, which was built by the
        trapezoidal rule - exact for the piecewise-linear interpolation the
        RASP format specifies [3].
        """
        return float(self._cumulative_impulse[-1])

    @property
    def average_thrust(self) -> float:
        """Total impulse divided by burn time [N]. Sutton & Biblarz [1], Eq. 2-5."""
        return self.total_impulse / self.burn_time

    @property
    def peak_thrust(self) -> float:
        """Maximum tabulated thrust [N]."""
        return float(np.max(self.thrusts))

    def thrust_at(self, t: float) -> float:
        """Thrust at a single time [N], zero outside the burn.

        Parameters
        ----------
        t:
            Time since ignition [s].

        Returns
        -------
        float
            Interpolated thrust [N].
        """
        if t < 0.0 or t > self.burn_time:
            return 0.0
        return float(np.interp(t, self.times, self.thrusts))

    def thrust_at_array(self, t: NDArray[np.float64]) -> NDArray[np.float64]:
        """Vectorised form of :meth:`thrust_at`.

        Parameters
        ----------
        t:
            Array of times since ignition [s].

        Returns
        -------
        numpy.ndarray
            Interpolated thrust at each time [N], zero outside the burn.
        """
        t_arr = np.asarray(t, dtype=np.float64)
        out = np.interp(t_arr, self.times, self.thrusts, left=0.0, right=0.0)
        return np.where((t_arr < 0.0) | (t_arr > self.burn_time), 0.0, out)

    def impulse_to(self, t: float) -> float:
        """Impulse delivered between ignition and time ``t`` [N*s].

        Used to track propellant consumption, which is proportional to
        delivered impulse for a constant specific impulse [1], Eq. 2-2.

        Parameters
        ----------
        t:
            Time since ignition [s].

        Returns
        -------
        float
            Delivered impulse [N*s], clamped to ``[0, total_impulse]``.
        """
        if t <= 0.0:
            return 0.0
        if t >= self.burn_time:
            return self.total_impulse

        # Look up the cumulative impulse at the preceding sample, then add the
        # partial trapezoid from there to t. O(log n) rather than O(n).
        idx = int(np.searchsorted(self.times, t))
        t_prev = float(self.times[idx - 1])
        f_prev = float(self.thrusts[idx - 1])
        f_now = self.thrust_at(t)
        partial = 0.5 * (f_prev + f_now) * (t - t_prev)
        return float(self._cumulative_impulse[idx - 1]) + partial

    def resampled(self, n_points: int) -> ThrustCurve:
        """Return a uniformly resampled copy with ``n_points`` samples.

        Parameters
        ----------
        n_points:
            Number of samples, at least 2.

        Returns
        -------
        ThrustCurve
            Resampled curve with the same provenance.
        """
        if n_points < 2:
            raise ValueError("n_points must be at least 2")
        times = np.linspace(0.0, self.burn_time, n_points)
        return ThrustCurve(
            times=times,
            thrusts=self.thrust_at_array(times),
            source=self.source,
        )


def impulse_class(total_impulse: float) -> str:
    """Return the NAR/TRA impulse class letter for a total impulse.

    Class boundaries double with each letter: 1/4A is up to 0.625 N*s, A is up
    to 2.5 N*s, B to 5, C to 10, D to 20, and so on [2].

    Parameters
    ----------
    total_impulse:
        Total impulse [N*s].

    Returns
    -------
    str
        Class letter, e.g. ``"C"``. Returns ``"1/4A"`` and ``"1/2A"`` for the
        two sub-A classes.

    Raises
    ------
    ValueError
        If ``total_impulse`` is not positive.
    """
    if total_impulse <= 0.0:
        raise ValueError("total_impulse must be positive")
    if total_impulse <= 0.3125:
        return "1/8A"
    if total_impulse <= 0.625:
        return "1/4A"
    if total_impulse <= 1.25:
        return "1/2A"

    # A tops out at 2.5 N*s; each subsequent letter doubles the ceiling.
    letters = "ABCDEFGHIJKLMNO"
    ceiling = 2.5
    for letter in letters:
        if total_impulse <= ceiling:
            return letter
        ceiling *= 2.0
    return "O+"


@dataclass(frozen=True, slots=True)
class Motor:
    """A solid rocket motor with certified performance data.

    Attributes
    ----------
    designation:
        Motor code without the delay, e.g. ``"C6"``.
    manufacturer:
        Manufacturer name.
    diameter:
        Case outside diameter [m].
    length:
        Case length [m].
    total_mass:
        Loaded mass including propellant, delay grain and ejection charge [kg].
    propellant_mass:
        Mass of propellant consumed during the thrust phase [kg].
    thrust_curve:
        Thrust history; see :class:`ThrustCurve`.
    delays:
        Available ejection delays [s]. ``0.0`` denotes a booster motor with no
        delay grain.
    source:
        Citation for the certified scalar data.
    """

    designation: str
    manufacturer: str
    diameter: float
    length: float
    total_mass: float
    propellant_mass: float
    thrust_curve: ThrustCurve
    delays: tuple[float, ...]
    source: str = "[2]"

    def __post_init__(self) -> None:
        """Validate the motor definition."""
        if self.diameter <= 0.0 or self.length <= 0.0:
            raise ValueError(f"{self.designation}: dimensions must be positive")
        if self.total_mass <= 0.0:
            raise ValueError(f"{self.designation}: total_mass must be positive")
        if not 0.0 < self.propellant_mass < self.total_mass:
            raise ValueError(
                f"{self.designation}: propellant_mass ({self.propellant_mass} kg) "
                f"must be positive and less than total_mass ({self.total_mass} kg)"
            )
        if not self.delays:
            raise ValueError(f"{self.designation}: at least one delay is required")
        if any(d < 0.0 for d in self.delays):
            raise ValueError(f"{self.designation}: delays must not be negative")

    # -- Derived performance -------------------------------------------------

    @property
    def total_impulse(self) -> float:
        """Total impulse [N*s]."""
        return self.thrust_curve.total_impulse

    @property
    def average_thrust(self) -> float:
        """Average thrust over the burn [N]."""
        return self.thrust_curve.average_thrust

    @property
    def peak_thrust(self) -> float:
        """Maximum thrust [N]."""
        return self.thrust_curve.peak_thrust

    @property
    def burn_time(self) -> float:
        """Burn duration [s]."""
        return self.thrust_curve.burn_time

    @property
    def burnout_mass(self) -> float:
        """Mass after the propellant is consumed [kg].

        Excludes the ejection charge, which is still present at burnout and is
        only expelled at deployment. Treating it as retained is conservative
        for apogee prediction.
        """
        return self.total_mass - self.propellant_mass

    @property
    def specific_impulse(self) -> float:
        """Specific impulse [s].

        ``Isp = I_total / (m_propellant * g0)``. Sutton & Biblarz [1], Eq. 2-5.
        For Estes black powder this lands around 80 s, an order of magnitude
        below a composite propellant, which is expected.
        """
        return self.total_impulse / (self.propellant_mass * G0)

    @property
    def impulse_class(self) -> str:
        """NAR impulse class letter, e.g. ``"C"``."""
        return impulse_class(self.total_impulse)

    @property
    def propellant_mass_fraction(self) -> float:
        """Propellant mass divided by loaded mass [-]."""
        return self.propellant_mass / self.total_mass

    @property
    def cross_sectional_area(self) -> float:
        """Case cross-sectional area [m^2]."""
        return np.pi * (self.diameter / 2.0) ** 2

    # -- Time histories ------------------------------------------------------

    def thrust_at(self, t: float) -> float:
        """Thrust at time ``t`` since ignition [N]."""
        return self.thrust_curve.thrust_at(t)

    def mass_at(self, t: float) -> float:
        """Total motor mass at time ``t`` since ignition [kg].

        Propellant is consumed in proportion to delivered impulse, which
        follows from a constant specific impulse [1], Eq. 2-2:
        ``dm/dt = -F(t) / (Isp * g0)``. Integrating gives
        ``m(t) = m_total - m_prop * I(t) / I_total``.

        Parameters
        ----------
        t:
            Time since ignition [s].

        Returns
        -------
        float
            Motor mass [kg], clamped to ``[burnout_mass, total_mass]``.
        """
        if t <= 0.0:
            return self.total_mass
        if t >= self.burn_time:
            return self.burnout_mass
        burned_fraction = self.thrust_curve.impulse_to(t) / self.total_impulse
        return self.total_mass - self.propellant_mass * burned_fraction

    def mass_flow_at(self, t: float) -> float:
        """Propellant mass flow rate at time ``t`` [kg/s], positive.

        From ``dm/dt = -F(t) / (Isp * g0)`` [1], Eq. 2-2.

        Parameters
        ----------
        t:
            Time since ignition [s].

        Returns
        -------
        float
            Mass depletion rate [kg/s]; zero outside the burn.
        """
        return self.thrust_at(t) / (self.specific_impulse * G0)

    def centre_of_mass_offset(self, t: float) -> float:
        """Distance of the motor's centre of mass aft of its forward face [m].

        Estes black-powder motors burn from the nozzle end forward once the
        starting core is consumed, but the casing, clay nozzle and delay grain
        together dominate the mass budget and do not move. Treating the motor
        centre of mass as fixed at the geometric centre introduces an error
        below one tenth of a body calibre for this motor class, so that is the
        model used here. The signature takes ``t`` so that a future
        grain-resolved model can be substituted without changing callers.

        Parameters
        ----------
        t:
            Time since ignition [s]. Unused by the current model.

        Returns
        -------
        float
            Offset aft of the motor's forward face [m].
        """
        del t  # Fixed-centroid model; see the note above.
        return self.length / 2.0

    def provenance_warning(self) -> str:
        """Return a caveat string when the thrust curve is not measured data.

        Returns
        -------
        str
            Empty when the curve came from a RASP file; otherwise a sentence
            suitable for inclusion in a report.
        """
        if self.thrust_curve.source is ThrustCurveSource.MEASURED:
            return ""
        return (
            f"The {self.designation} thrust curve is synthesised from certified "
            f"scalars (total impulse {self.total_impulse:.2f} N*s, peak thrust "
            f"{self.peak_thrust:.1f} N, burn time {self.burn_time:.2f} s), not "
            f"measured static-test data. Integrated results are reliable; "
            f"instantaneous peak-load results should be confirmed against a "
            f"measured .eng file from ThrustCurve.org."
        )

    def with_delay(self, delay: float) -> MotorConfiguration:
        """Pair this motor with one of its available ejection delays.

        Parameters
        ----------
        delay:
            Ejection delay [s]. Must be one of :attr:`delays`.

        Returns
        -------
        MotorConfiguration
            The motor-plus-delay combination actually flown.

        Raises
        ------
        ValueError
            If ``delay`` is not an available delay for this motor.
        """
        if not any(np.isclose(delay, d) for d in self.delays):
            raise ValueError(
                f"{self.designation} is not available with a {delay} s delay; "
                f"available delays are {list(self.delays)}"
            )
        return MotorConfiguration(motor=self, delay=delay)

    def __str__(self) -> str:
        """Return the motor designation and headline performance."""
        return (
            f"{self.manufacturer} {self.designation} "
            f"({self.total_impulse:.1f} N*s {self.impulse_class}, "
            f"{self.average_thrust:.1f} N avg, {self.burn_time:.2f} s)"
        )


@dataclass(frozen=True, slots=True)
class MotorConfiguration:
    """A motor together with the ejection delay selected for a flight.

    Attributes
    ----------
    motor:
        The motor.
    delay:
        Ejection delay after burnout [s].
    """

    motor: Motor
    delay: float = field(default=0.0)

    @property
    def designation(self) -> str:
        """Full designation including delay, e.g. ``"C6-5"``."""
        if self.delay <= 0.0:
            return f"{self.motor.designation}-0"
        # Delays are quoted as integers on the case when they are whole.
        if float(self.delay).is_integer():
            return f"{self.motor.designation}-{int(self.delay)}"
        return f"{self.motor.designation}-{self.delay:g}"

    @property
    def ejection_time(self) -> float:
        """Time from ignition to ejection charge firing [s]."""
        return self.motor.burn_time + self.delay

    @property
    def burn_time(self) -> float:
        """Burn duration [s]."""
        return self.motor.burn_time

    @property
    def total_impulse(self) -> float:
        """Total impulse [N*s]."""
        return self.motor.total_impulse

    def thrust_at(self, t: float) -> float:
        """Thrust at time ``t`` since ignition [N].

        Delegates to the motor. Present so that a
        :class:`MotorConfiguration` can be used wherever the flown motor is
        needed without callers reaching through to ``.motor``.

        Parameters
        ----------
        t:
            Time since ignition [s].

        Returns
        -------
        float
            Thrust [N].
        """
        return self.motor.thrust_at(t)

    def mass_at(self, t: float) -> float:
        """Motor mass at time ``t`` since ignition [kg].

        Parameters
        ----------
        t:
            Time since ignition [s].

        Returns
        -------
        float
            Motor mass [kg].
        """
        return self.motor.mass_at(t)

    def __str__(self) -> str:
        """Return the full designation."""
        return self.designation
